
name: Spring Boot CI with Gradle

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
    - "**"
    paths:
      - springboot/**
  pull_request:
    branches: [ "main", "devx" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: init-checkout
      uses: actions/checkout@v3
    - name: init-java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: init-gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
    - name: build-boot
      run: |
        cd springboot
        gradle build -x test
